export * from './Info';
export * from './Pacientes';
export * from './Usuarios';
export * from './Inventario';
export * from './DetalleVentas';
export * from './RangoFacturas'
export * from './DetalleExpediente'
export * from './ImportDatos';
export * from './Optometristas';
export * from './Sucursales';
